services:
  web:
    build: .
    container_name: php_web_scraping
    ports:
      - "18084:80"
    volumes:
      - ./www:/var/www/html/
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mysql_db_scraping
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: login
      MYSQL_USER: usuario
      MYSQL_PASSWORD: contrasena
    ports:
      - "3307:3306"  # CAMBIADO: 3307 en host -> 3306 en contenedor
    volumes:
      - ./mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_scraping
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "18001:81"
    depends_on:
      - db